Create Kafka Producer and methods for sending messages
yastrebow/OneMicr pull request #6
Opened 2021-12-29 17:10 UTC by yastrebow

2021-12-29 19:46 UTC, MichaelDeyev requested changes

2021-12-29 19:46 UTC, MichaelDeyev commented on .jpb/jpb-settings.xml
> +    </component>
Это зачем?)

2021-12-29 19:46 UTC, MichaelDeyev commented on pom.xml
>          </dependency>
вроде вы не используйте эту зависимость...

2021-12-29 19:46 UTC, MichaelDeyev commented on pom.xml
> +        </dependency>
Лучше убрать эти зависимости, пока не используйте сваггер

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/controller/EmployeeController.java
>  import org.springframework.web.bind.annotation.*;
Лучше избегать звёздочки в импортах

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/controller/EmployeeController.java
> +    public ResponseEntity<Object> create(@RequestBody EmployeeDto employeeDto) {
Почему здесь Object?

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/service/EmployeeService.java
> +    Object create(EmployeeDto employeeDto);
Почему возвращаете Object?

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +                + ", gender = " + employeeDto.getGender()
Лучше использовать String.format()

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +                + ", hireDate = " + employeeDto.getGender()
Лучше использовать String.format()

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +
Лучше убрать лишние пустые строки

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +        sendMessage("The record with id= " + id +" was deleted from Employee DB");
Почему бы не посылать в кафку полную информацию, а не только id?

2021-12-29 19:46 UTC, MichaelDeyev commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +}
Это можно не указывать

2022-01-02 14:19 UTC, yastrebow commented on .jpb/jpb-settings.xml
> +    </component>
Честно сказать, я даже не знаю, откуда это взялось. Удалил.

2022-01-02 14:19 UTC, yastrebow commented on pom.xml
>          </dependency>
Убрал

2022-01-02 14:21 UTC, yastrebow commented on pom.xml
> +        </dependency>
Со Сваггером хочу ещё попробовать. Пока оставлю)

2022-01-02 14:22 UTC, yastrebow commented on src/main/java/ru/yastrebov/onemicr/controller/EmployeeController.java
>  import org.springframework.web.bind.annotation.*;
Ок. Это Идея, по-моему, балуется. Посмотрю, как отключить эту опцию.

2022-01-02 14:38 UTC, yastrebow commented on src/main/java/ru/yastrebov/onemicr/controller/EmployeeController.java
> +    public ResponseEntity<Object> create(@RequestBody EmployeeDto employeeDto) {
Это получилось опытным путем. Иначе Идея на этот метод ругается. По-другому победить не удалось(

2022-01-02 15:28 UTC, yastrebow commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +                + ", gender = " + employeeDto.getGender()
Поменял

2022-01-02 15:28 UTC, yastrebow commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +                + ", hireDate = " + employeeDto.getGender()
Поменял

2022-01-02 15:30 UTC, yastrebow commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +
100-ю убрал. А вообще - пока интуитивно расставляю пустые строки, отделяя блоки кода. Есть какие-то правила на этот счет?

2022-01-02 15:36 UTC, yastrebow commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +        sendMessage("The record with id= " + id +" was deleted from Employee DB");
Верно))) Не допёр, что можно выдернуть всю инфу из employeeForDelete. Заодно вопрос: а вот эта история для чего:
final EmployeeDto deletedEmployeeDTO = mapper.employeeToDto(employeeForDelete);

2022-01-02 15:43 UTC, yastrebow commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +}
Это я и не указывал) ... или указывал?

2022-01-02 15:43 UTC, yastrebow commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +}
Удалил

2022-01-02 20:35 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/controller/EmployeeController.java
> +    public ResponseEntity<Object> create(@RequestBody EmployeeDto employeeDto) {
Надо обсудить. Object лучше не оставлять

2022-01-02 20:35 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/onemicr/service/impl/EmployeeServiceImpl.java
> +                employeeDto.getPosition().toString(), employeeDto.getProject().toString(), employeeDto.getHireDate().toString(), employeeDto.getGender().toString());
Создание сообщения на отправку в кафку лучше вынести в отдельный метод, иначе это привед к дублированию кода как в данном случае. В других методах аналогично.

2022-01-02 20:35 UTC, MichaelDeyev commented on src/main/resources/application.yaml
> +      bootstrap-servers: localhost:8082
у кафки вроде по умолчанию сервер на порту 9092

2022-01-03 11:36 UTC, merged